# Generated by Django 5.2.9 on 2026-01-11 09:12

import contest.models.user
import contest.utils
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Displayed at payment method selection page",
                        null=True,
                        upload_to="",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "name_pl",
                    models.CharField(max_length=50, verbose_name="Polish name"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code is used by the software, do not change!",
                        max_length=10,
                        unique=True,
                        verbose_name="Method code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Phone number"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Address"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("pl", "Polish"), ("en", "English")],
                        max_length=2,
                        verbose_name="I would like to get feedback on my meads in",
                    ),
                ),
                (
                    "gdpr_consent",
                    models.BooleanField(
                        default=False,
                        validators=[contest.models.user.validate_gdpr_consent],
                        verbose_name="Privacy Policy accepted",
                    ),
                ),
                ("gdpr_consent_date", models.DateTimeField(auto_now_add=True)),
                (
                    "rebate_code_text",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Rebate code"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user",
            },
            managers=[
                ("objects", contest.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("contest.user",),
            managers=[
                ("objects", contest.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="will be used in contest URL, can be derrived automatically from titile",
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "description_pl",
                    models.TextField(null=True, verbose_name="Description in polish"),
                ),
                ("rules", models.TextField(blank=True, verbose_name="Rules")),
                (
                    "rules_pl",
                    models.TextField(blank=True, verbose_name="Rules in polish"),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "entry_fee_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Entry fee amount"
                    ),
                ),
                (
                    "entry_fee_currency",
                    models.CharField(max_length=3, verbose_name="Fee currency code"),
                ),
                (
                    "payment_transfer_info",
                    models.TextField(
                        blank=True,
                        help_text="Mandatory if contest allows transfer payment method.",
                        verbose_name="Transfer payment instructions",
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Discount rate with promo code (in %)",
                    ),
                ),
                (
                    "entry_global_limit",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Leave blank if no limit should be applied",
                        null=True,
                        verbose_name="Limit of entries in the contest",
                    ),
                ),
                (
                    "entry_user_limit",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Leave blank if no limit should be applied",
                        null=True,
                        verbose_name="Limit of entries per participant",
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="Delivery address")),
                (
                    "judge_registration_date_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Judge registration from"
                    ),
                ),
                (
                    "judge_registration_date_to",
                    models.DateField(blank=True, null=True, verbose_name="to"),
                ),
                (
                    "registration_date_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Entry registration from"
                    ),
                ),
                (
                    "registration_date_to",
                    models.DateField(blank=True, null=True, verbose_name="to"),
                ),
                (
                    "delivery_date_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Delivery from"
                    ),
                ),
                (
                    "delivery_date_to",
                    models.DateField(blank=True, null=True, verbose_name="to"),
                ),
                (
                    "judging_date_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Judging sessions from"
                    ),
                ),
                (
                    "judging_date_to",
                    models.DateField(blank=True, null=True, verbose_name="to"),
                ),
                (
                    "competition_is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Ignores auto-publish date",
                        verbose_name="Competition page is published",
                    ),
                ),
                (
                    "competition_autopublish_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fill only if you want the competition page to be published automatically at that time",
                        null=True,
                        verbose_name="When to publish competition page automatically",
                    ),
                ),
                (
                    "result_is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Ignores auto-publish date",
                        verbose_name="Competition results are published",
                    ),
                ),
                (
                    "result_autopublish_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fill only if you want the competition <b>results</b> to be published automatically at that time",
                        null=True,
                        verbose_name="When to publish results automatically",
                    ),
                ),
                (
                    "is_judging_eliminations",
                    models.BooleanField(
                        default=False,
                        verbose_name="Enable judges to judge elimination round.",
                    ),
                ),
                (
                    "is_judging_finals",
                    models.BooleanField(
                        default=False,
                        verbose_name="Enable judges to judge final round.",
                    ),
                ),
                (
                    "is_judging_bos",
                    models.BooleanField(
                        default=False,
                        verbose_name="Enable judges to judge Best Of Show.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_contests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="modified_contests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contest",
                "verbose_name_plural": "contests",
                "ordering": ("-judging_date_from", "-delivery_date_to"),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entries_limit",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Entries limit per user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="modified_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="contest.contest",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["contest__title", "style__name"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.IntegerField(
                        default=contest.utils.code_generator,
                        editable=False,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "sweetness",
                    models.CharField(
                        choices=[
                            ("dry", "Dry"),
                            ("medium", "Medium"),
                            ("sweet", "Sweet"),
                        ],
                        max_length=10,
                        verbose_name="Sweetness",
                    ),
                ),
                (
                    "carbonation",
                    models.CharField(
                        choices=[
                            ("still", "Still"),
                            ("petillant", "Petillant"),
                            ("sparkling", "Sparkling"),
                        ],
                        max_length=10,
                        verbose_name="Carbonation",
                    ),
                ),
                (
                    "extra_info",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Ingredients"
                    ),
                ),
                (
                    "alcohol_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Alcohol content (ABV)",
                    ),
                ),
                ("place", models.PositiveIntegerField(default=0, verbose_name="Place")),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Is paid"
                    ),
                ),
                (
                    "is_received",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Is received"
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "brewer",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="contest.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
                "ordering": [
                    "category__contest__title",
                    "category__style__name",
                    "brewer",
                    "name",
                ],
            },
        ),
        migrations.CreateModel(
            name="EntriesPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contest.contest",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entries",
                    models.ManyToManyField(related_name="packages", to="contest.entry"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contest",
            name="bos_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contest.entry",
                verbose_name="Best Of Show winner",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalScoreSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid1, editable=False),
                ),
                (
                    "final_round",
                    models.BooleanField(default=False, verbose_name="Final round"),
                ),
                ("appearance", models.TextField(blank=True, verbose_name="Appearance")),
                (
                    "appearance_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(12)],
                        verbose_name="Appearance score",
                    ),
                ),
                ("aroma", models.TextField(blank=True, verbose_name="Aroma")),
                (
                    "aroma_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(30)],
                        verbose_name="Aroma score",
                    ),
                ),
                (
                    "flavor",
                    models.TextField(blank=True, verbose_name="Flavor and body"),
                ),
                (
                    "flavor_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(32)],
                        verbose_name="Flavor and body score",
                    ),
                ),
                ("finish", models.TextField(blank=True, verbose_name="Finish")),
                (
                    "finish_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(14)],
                        verbose_name="Finish score",
                    ),
                ),
                (
                    "overall",
                    models.TextField(blank=True, verbose_name="Overall impression"),
                ),
                (
                    "overall_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(12)],
                        verbose_name="Overal impression score",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contest.entry",
                        verbose_name="Entry",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Score Sheet",
                "verbose_name_plural": "historical Score Sheets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="JudgeCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_mead_bjcp",
                    models.BooleanField(default=False, verbose_name="BJCP Mead"),
                ),
                ("is_mjp", models.BooleanField(default=False, verbose_name="MJP")),
                ("is_other", models.BooleanField(default=False, verbose_name="Other")),
                (
                    "mjp_level",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="MJP level",
                    ),
                ),
                (
                    "other_description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="Currency")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("canceled", "Canceled"),
                            ("ok", "OK"),
                            ("failed", "Failed"),
                            ("awaiting", "Confirmation pending"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.CharField(max_length=50, null=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="contest.contest",
                        verbose_name="Contest",
                    ),
                ),
                (
                    "entries",
                    models.ManyToManyField(
                        related_name="payments",
                        to="contest.entry",
                        verbose_name="Entries",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contest.paymentmethod",
                        verbose_name="Method",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="contest",
            name="payment_methods",
            field=models.ManyToManyField(
                related_name="contests",
                to="contest.paymentmethod",
                verbose_name="Allowed payment methods",
            ),
        ),
        migrations.CreateModel(
            name="RebateCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=contest.utils.rebate_code_generator,
                        editable=False,
                        max_length=10,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Is used")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rebate_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rebate Code",
                "verbose_name_plural": "Rebate Codes",
            },
        ),
        migrations.CreateModel(
            name="ScoreSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "final_round",
                    models.BooleanField(default=False, verbose_name="Final round"),
                ),
                ("appearance", models.TextField(blank=True, verbose_name="Appearance")),
                (
                    "appearance_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(12)],
                        verbose_name="Appearance score",
                    ),
                ),
                ("aroma", models.TextField(blank=True, verbose_name="Aroma")),
                (
                    "aroma_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(30)],
                        verbose_name="Aroma score",
                    ),
                ),
                (
                    "flavor",
                    models.TextField(blank=True, verbose_name="Flavor and body"),
                ),
                (
                    "flavor_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(32)],
                        verbose_name="Flavor and body score",
                    ),
                ),
                ("finish", models.TextField(blank=True, verbose_name="Finish")),
                (
                    "finish_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(14)],
                        verbose_name="Finish score",
                    ),
                ),
                (
                    "overall",
                    models.TextField(blank=True, verbose_name="Overall impression"),
                ),
                (
                    "overall_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(12)],
                        verbose_name="Overal impression score",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoresheets",
                        to="contest.entry",
                        verbose_name="Entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score Sheet",
                "verbose_name_plural": "Score Sheets",
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="will be used in contest URL, can be derrived automatically from titile",
                        unique=True,
                    ),
                ),
                (
                    "show",
                    models.BooleanField(
                        default=True,
                        verbose_name="Allow to use this category in competitions",
                    ),
                ),
                (
                    "extra_info_is_required",
                    models.BooleanField(
                        default=False,
                        verbose_name="Require extra information for entries?",
                    ),
                ),
                (
                    "extra_info_hint",
                    models.CharField(
                        blank=True,
                        help_text="This will instruct the participants what information they need to provide for an entry.</br>Fill only if you require extra information for entries",
                        max_length=255,
                        verbose_name="Required information hint",
                    ),
                ),
                (
                    "extra_info_hint_pl",
                    models.CharField(
                        blank=True,
                        help_text="This will instruct the participants what information they need to provide for an entry.</br>Fill only if you require extra information for entries",
                        max_length=255,
                        verbose_name="Required information hint in Polish",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description in english"),
                ),
                (
                    "description_pl",
                    models.TextField(null=True, verbose_name="Description in polish"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="modified_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "style",
                "verbose_name_plural": "styles",
            },
        ),
        migrations.AddField(
            model_name="contest",
            name="styles",
            field=models.ManyToManyField(
                through="contest.Category",
                through_fields=("contest", "style"),
                to="contest.style",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="style",
            field=models.ForeignKey(
                limit_choices_to={"show": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="contest.style",
            ),
        ),
        migrations.CreateModel(
            name="JudgeInCompetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("application", "Application"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="application",
                        max_length=20,
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contest.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Judge",
                "verbose_name_plural": "Judges",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "contest"),
                        name="unique_judge_application_per_contest",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("style", "contest"), name="unique_contest_style"
            ),
        ),
    ]
