# Generated by Django 4.2 on 2023-11-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='delivery_address',
            field=models.TextField(default=' ', verbose_name='Delivery address'),
            preserve_default=False,
        ),
    ]
