# Generated by Django 5.2.9 on 2026-02-08 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0002_remove_username_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="contest.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.CreateModel(
            name="ContestMembershipRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("JUDGE", "JUDGE"),
                            ("JUDGE_FINALS", "JUDGE_FINALS"),
                            ("JUDGE_BOS", "JUDGE_BOS"),
                            ("HEAD_JUDGE", "HEAD_JUDGE"),
                            ("MANAGER", "MANAGER"),
                            ("ENTRY_MANAGER", "ENTRY_MANAGER"),
                            ("ENTRY_CODER", "ENTRY_CODER"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="contest.contestmembership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff role",
                "verbose_name_plural": "Staff roles",
            },
        ),
        migrations.AddIndex(
            model_name="contestmembership",
            index=models.Index(
                fields=["user", "contest"], name="contest_con_user_id_d55de9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contestmembership",
            unique_together={("user", "contest")},
        ),
        migrations.AlterUniqueTogether(
            name="contestmembershiprole",
            unique_together={("membership", "role")},
        ),
    ]
