# Generated by Django 4.2 on 2023-11-12 15:47

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_user_address_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contest.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='entry_fee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Entry fee amount'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='Is received'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone number'),
        ),
    ]
