# Generated by Django 4.2 on 2023-11-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='entry_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='entry_fee_currency',
            field=models.CharField(default='N/A', max_length=3, verbose_name='Fee currency code'),
            preserve_default=False,
        ),
    ]
