# Generated by Django 4.2 on 2023-11-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contest_entry_fee_amount_contest_entry_fee_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='entry_global_limit',
            field=models.SmallIntegerField(blank=True, help_text='Leave blank if no limit should be applied', null=True, verbose_name='Limit of entries in the contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='entry_user_limit',
            field=models.SmallIntegerField(blank=True, help_text='Leave blank if no limit should be applied', null=True, verbose_name='Limit of entries per participant'),
        ),
    ]
