# Generated by Django 5.2.9 on 2026-02-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0003_contestmembership_contestmembershiprole_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="secret_code",
            field=models.CharField(
                editable=False, max_length=4, null=True, verbose_name="Judging code"
            ),
        ),
        migrations.AlterField(
            model_name="contestmembershiprole",
            name="role",
            field=models.CharField(
                choices=[
                    ("judge", "JUDGE"),
                    ("judge_finals", "JUDGE_FINALS"),
                    ("judge_bos", "JUDGE_BOS"),
                    ("head_judge", "HEAD_JUDGE"),
                    ("manager", "MANAGER"),
                    ("entry_manager", "ENTRY_MANAGER"),
                    ("entry_coder", "ENTRY_CODER"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="code",
            field=models.IntegerField(editable=False, verbose_name="code"),
        ),
    ]
