# Generated by Django 4.2 on 2023-11-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_participant_alter_contest_entry_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
