# Generated by Django 4.2 on 2023-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_entry_global_limit_contest_entry_user_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='extra_info',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Additional information'),
        ),
    ]
