# Generated by Django 4.2 on 2023-11-13 22:10

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('pl', 'Polish'), ('en', 'English')], max_length=2, verbose_name='I would like to get feedback on my meads in'),
        ),
    ]
