# Generated by Django 5.2.9 on 2026-03-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0004_entry_secret_code_alter_contestmembershiprole_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="style",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Name"),
        ),
    ]
