# Generated by Django 4.2 on 2023-04-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_competition_autopublish_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
