# Generated by Django 5.2.9 on 2026-03-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0005_alter_style_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgecertification",
            name="tshirt_size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                default="M",
                max_length=3,
                verbose_name="T-shirt size",
            ),
        ),
    ]
