# Generated by Django 4.2 on 2023-11-14 18:16

import contest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contest_description_pl_style_description_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='code',
            field=models.IntegerField(default=contest.models.code_generator, verbose_name='code'),
        ),
    ]
