# Generated by Django 5.2.9 on 2026-03-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_judgecertification_tshirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='slug',
            field=models.SlugField(blank=True, help_text='will be used in contest URL, can be derrived automatically from titile', max_length=255, unique=True),
        ),
    ]
