# Generated by Django 5.2.9 on 2026-03-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_alter_style_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['contest__title', 'order', 'style__name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=10, help_text='Lower number means higher priority', verbose_name='Order'),
        ),
    ]
