# Generated by Django 4.2 on 2023-04-14 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0007_alter_contest_created_by_alter_contest_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('show', models.BooleanField(default=True, verbose_name='Allow to use this category in competitions')),
                ('extra_info_is_required', models.BooleanField(default=False, verbose_name='Require extra information for entries?')),
                ('extra_info_hint', models.CharField(blank=True, help_text='This will instruct the participants what information they need to provide for an entry.</br>Fill only if you require extra information for entries', max_length=255, verbose_name='Required information hint')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contests', models.ManyToManyField(related_name='categories', to='contest.contest')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
