# Generated by Django 4.2 on 2023-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='contests',
        ),
        migrations.AddField(
            model_name='contest',
            name='categories',
            field=models.ManyToManyField(related_name='contests', to='contest.category'),
        ),
    ]
