# Generated by Django 5.2.9 on 2026-03-13 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgecertification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_certification', to=settings.AUTH_USER_MODEL),
        ),
    ]
