# Generated by Django 5.2.9 on 2026-03-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_alter_judgecertification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Phone number'),
        ),
    ]
