# Generated by Django 4.2 on 2023-04-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0009_remove_category_contests_contest_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='extra_info_hint',
        ),
        migrations.RemoveField(
            model_name='category',
            name='extra_info_is_required',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='show',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='contest.contest'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('show', models.BooleanField(default=True, verbose_name='Allow to use this category in competitions')),
                ('extra_info_is_required', models.BooleanField(default=False, verbose_name='Require extra information for entries?')),
                ('extra_info_hint', models.CharField(blank=True, help_text='This will instruct the participants what information they need to provide for an entry.</br>Fill only if you require extra information for entries', max_length=255, verbose_name='Required information hint')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_styles', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_styles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'style',
                'verbose_name_plural': 'styles',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='style',
            field=models.ForeignKey(limit_choices_to={'show': True}, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='contest.style'),
            preserve_default=False,
        ),
    ]
