# Generated by Django 4.2 on 2023-11-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_paymentmethod_contest_payment_transfer_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
