# Generated by Django 4.2 on 2023-11-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='extra_info_hint_pl',
            field=models.CharField(blank=True, help_text='This will instruct the participants what information they need to provide for an entry.</br>Fill only if you require extra information for entries', max_length=255, verbose_name='Required information hint in Polish'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(verbose_name='Description in english'),
        ),
    ]
