# Generated by Django 5.2.9 on 2026-03-19 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('send_emails', 'Send emails')], max_length=100, unique=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
