# Generated by Django 4.2 on 2023-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='contest',
            name='styles',
            field=models.ManyToManyField(through='contest.Category', to='contest.style'),
        ),
    ]
