# Generated by Django 4.2 on 2023-12-09 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_style_extra_info_hint_pl_alter_entry_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('has_medal', models.BooleanField(default=False, verbose_name='Medal')),
                ('description', models.TextField(verbose_name='Description')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoresheets', to='contest.entry', verbose_name='Entry')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalScoreSheet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid1, editable=False)),
                ('has_medal', models.BooleanField(default=False, verbose_name='Medal')),
                ('description', models.TextField(verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contest.entry', verbose_name='Entry')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical score sheet',
                'verbose_name_plural': 'historical score sheets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
