# Generated by Django 4.2 on 2024-09-10 22:03

import contest.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_scoresheet_historicalscoresheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='alcohol_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Alcohol content'),
        ),
        migrations.AddField(
            model_name='entry',
            name='carbonation',
            field=models.CharField(choices=[('still', 'Still'), ('petillant', 'Petillant'), ('sparkling', 'Sparkling')], default='still', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='sweetness',
            field=models.CharField(choices=[('dry', 'Dry'), ('medium', 'Medium'), ('sweet', 'Sweet')], default='medium', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='brewer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='code',
            field=models.IntegerField(default=contest.models.code_generator, editable=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='extra_info',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_paid',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is paid'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_received',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is received'),
        ),
    ]
