# Generated by Django 4.2 on 2023-04-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_entry_category_unique_contest_style_entry_brewer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['category__contest__title', 'category__style__name', 'brewer', 'name'], 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='style',
            name='slug',
            field=models.SlugField(blank=True, help_text='will be used in contest URL, can be derrived automatically from titile', unique=True),
        ),
    ]
