# Generated by Django 4.2 on 2024-09-13 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0014_contest_rules_contest_rules_pl_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalscoresheet",
            name="description",
        ),
        migrations.RemoveField(
            model_name="historicalscoresheet",
            name="has_medal",
        ),
        migrations.RemoveField(
            model_name="scoresheet",
            name="description",
        ),
        migrations.RemoveField(
            model_name="scoresheet",
            name="has_medal",
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="appearance",
            field=models.TextField(blank=True, verbose_name="Appearance"),
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="appearance_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(12)],
                verbose_name="Appearance score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="aroma",
            field=models.TextField(blank=True, verbose_name="Aroma"),
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="aroma_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(30)],
                verbose_name="Aroma score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="final_round",
            field=models.BooleanField(default=False, verbose_name="Final round"),
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="finish",
            field=models.TextField(blank=True, verbose_name="Finish"),
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="finish_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(14)],
                verbose_name="Finish score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="flavor",
            field=models.TextField(blank=True, verbose_name="Flavor and body"),
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="flavor_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(32)],
                verbose_name="Flavor and body score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="overall",
            field=models.TextField(blank=True, verbose_name="Overall impression"),
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="overall_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(12)],
                verbose_name="Overal impression score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalscoresheet",
            name="place",
            field=models.PositiveIntegerField(default=0, verbose_name="Place"),
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="appearance",
            field=models.TextField(blank=True, verbose_name="Appearance"),
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="appearance_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(12)],
                verbose_name="Appearance score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="aroma",
            field=models.TextField(blank=True, verbose_name="Aroma"),
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="aroma_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(30)],
                verbose_name="Aroma score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="final_round",
            field=models.BooleanField(default=False, verbose_name="Final round"),
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="finish",
            field=models.TextField(blank=True, verbose_name="Finish"),
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="finish_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(14)],
                verbose_name="Finish score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="flavor",
            field=models.TextField(blank=True, verbose_name="Flavor and body"),
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="flavor_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(32)],
                verbose_name="Flavor and body score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="overall",
            field=models.TextField(blank=True, verbose_name="Overall impression"),
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="overall_score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(12)],
                verbose_name="Overal impression score",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scoresheet",
            name="place",
            field=models.PositiveIntegerField(default=0, verbose_name="Place"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="alcohol_content",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Alcohol content (ABV)",
            ),
        ),
    ]
