# Generated by Django 4.2 on 2023-04-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_alter_contest_slug_alter_style_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', help_text='will be used in contest URL, can be derrived automatically from titile', unique=True),
        ),
    ]
