# Generated by Django 4.2 on 2024-09-20 20:32

import contest.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0015_remove_historicalscoresheet_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gdpr_consent",
            field=models.BooleanField(
                default=False,
                validators=[contest.models.validate_gdpr_consent],
                verbose_name="Privacy Policy accepted",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gdpr_consent_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
