# Generated by Django 4.2 on 2024-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0016_user_gdpr_consent_user_gdpr_consent_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gdpr_consent_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
