# Generated by Django 4.2 on 2023-09-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_alter_contest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(blank=True, help_text='will be used in contest URL, can be derrived automatically from titile', unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='slug',
            field=models.SlugField(blank=True, help_text='will be used in contest URL, can be derrived automatically from titile', unique=True),
        ),
    ]
