# Generated by Django 4.2 on 2024-10-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0017_alter_user_address_alter_user_gdpr_consent_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="is_judging_eliminations",
            field=models.BooleanField(
                default=False, verbose_name="Enable judges to judge elimination round."
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="is_judging_finals",
            field=models.BooleanField(
                default=False, verbose_name="Enable judges to judge final round."
            ),
        ),
    ]
