# Generated by Django 4.2 on 2024-10-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0018_contest_is_judging_eliminations_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalscoresheet",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Score Sheet",
                "verbose_name_plural": "historical Score Sheets",
            },
        ),
        migrations.AlterModelOptions(
            name="scoresheet",
            options={
                "verbose_name": "Score Sheet",
                "verbose_name_plural": "Score Sheets",
            },
        ),
    ]
