# Generated by Django 4.2 on 2024-10-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0019_alter_historicalscoresheet_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
    ]
