# Generated by Django 4.2 on 2024-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0020_alter_paymentmethod_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalscoresheet",
            name="place",
        ),
        migrations.RemoveField(
            model_name="scoresheet",
            name="place",
        ),
        migrations.AddField(
            model_name="entry",
            name="place",
            field=models.PositiveIntegerField(default=0, verbose_name="Place"),
        ),
    ]
