# Generated by Django 4.2 on 2024-10-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0021_remove_historicalscoresheet_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="is_judging_bos",
            field=models.BooleanField(
                default=False, verbose_name="Enable judges to judge Best Of Show."
            ),
        ),
    ]
