# Generated by Django 4.2 on 2024-10-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0022_contest_is_judging_bos"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="bos_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contest.entry",
                verbose_name="Best Of Show winner",
            ),
        ),
    ]
