# Generated by Django 4.2 on 2024-12-02 10:44

import contest.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0023_contest_bos_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="discount_rate",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Discount rate with promo code (in %)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rebate_code_text",
            field=models.CharField(
                blank=True,
                help_text="Add rebate code if you have one",
                max_length=15,
                verbose_name="Rebate code",
            ),
        ),
        migrations.CreateModel(
            name="RebateCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=contest.models.rebate_code_generator,
                        editable=False,
                        max_length=10,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Is used")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rebate_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rebate Code",
                "verbose_name_plural": "Rebate Codes",
            },
        ),
    ]
