# Generated by Django 5.2.9 on 2025-12-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0024_rebate_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="judge_registration_date_from",
            field=models.DateField(
                blank=True, null=True, verbose_name="Judge registration from"
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="judge_registration_date_to",
            field=models.DateField(blank=True, null=True, verbose_name="to"),
        ),
        migrations.AlterField(
            model_name="contest",
            name="styles",
            field=models.ManyToManyField(
                through="contest.Category",
                through_fields=("contest", "style"),
                to="contest.style",
            ),
        ),
    ]
