# Generated by Django 5.2.9 on 2025-12-15 18:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0025_contest_judge_registration_date_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                help_text="will be used in contest URL, can be derrived automatically from titile",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="JudgeCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_mead_bjcp",
                    models.BooleanField(default=False, verbose_name="BJCP MEAD"),
                ),
                ("is_mjp", models.BooleanField(default=False, verbose_name="MJP")),
                ("is_other", models.BooleanField(default=False, verbose_name="Other")),
                (
                    "mjp_level",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="MJP level",
                    ),
                ),
                (
                    "other_description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
