# Generated by Django 5.2.9 on 2026-01-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0027_judgeincompetition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="judgeincompetition",
            options={"verbose_name": "Judge", "verbose_name_plural": "Judges"},
        ),
        migrations.AlterField(
            model_name="judgecertification",
            name="is_mead_bjcp",
            field=models.BooleanField(default=False, verbose_name="BJCP Mead"),
        ),
        migrations.AddConstraint(
            model_name="judgeincompetition",
            constraint=models.UniqueConstraint(
                fields=("user", "contest"), name="unique_judge_application_per_contest"
            ),
        ),
    ]
